/****************************************************************************
**
** Metadata for ActSupportMsgLib generated by dumpcpp v5.14.2 using
** dumpcpp.exe {15C5A7A2-53A5-445C-B294-F383F951AC92}
** from the type library E:\MX Componetnt 4.19v\Act\Control\ActSupportMsg.dll
**
****************************************************************************/

#define QAX_DUMPCPP_ACTSUPPORTMSGLIB_NOINLINES
#include "actsupportmsglib.h"
#include <OAIdl.h>

using namespace ActSupportMsgLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[29];
    char stringdata0[416];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 31, 0),
QT_MOC_LITERAL(1, 32, 17, 0),
QT_MOC_LITERAL(2, 50, 21, 0),
QT_MOC_LITERAL(3, 72, 11, 0),
QT_MOC_LITERAL(4, 84, 14, 0),
QT_MOC_LITERAL(5, 99, 9, 0),
QT_MOC_LITERAL(6, 109, 0, 0),
QT_MOC_LITERAL(7, 110, 4, 0),
QT_MOC_LITERAL(8, 115, 6, 0),
QT_MOC_LITERAL(9, 122, 4, 0),
QT_MOC_LITERAL(10, 127, 4, 0),
QT_MOC_LITERAL(11, 132, 15, 0),
QT_MOC_LITERAL(12, 148, 4, 0),
QT_MOC_LITERAL(13, 153, 6, 0),
QT_MOC_LITERAL(14, 160, 4, 0),
QT_MOC_LITERAL(15, 165, 4, 0),
QT_MOC_LITERAL(16, 170, 15, 0),
QT_MOC_LITERAL(17, 186, 10, 0),
QT_MOC_LITERAL(18, 197, 8, 0),
QT_MOC_LITERAL(19, 206, 16, 0),
QT_MOC_LITERAL(20, 223, 32, 0),
QT_MOC_LITERAL(21, 256, 7, 0),
QT_MOC_LITERAL(22, 264, 33, 0),
QT_MOC_LITERAL(23, 298, 23, 0),
QT_MOC_LITERAL(24, 322, 16, 0),
QT_MOC_LITERAL(25, 339, 12, 0),
QT_MOC_LITERAL(26, 352, 9, 0),
QT_MOC_LITERAL(27, 362, 17, 0),
QT_MOC_LITERAL(28, 380, 34, 0)
    },
    "ActSupportMsgLib::ActSupportMsg\0Event Interface 1\0_IActSupportMsgEvents\0"
    "Interface 0\0IActSupportMsg\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0GetErrorMessage\0lErrorCode\0QString&\0lpszErrorMessage\0"
    "ActSupportMsgLib::IActSupportMsg\0control\0ActSupportMsgLib::ActMLSupportMsg\0"
    "_IActMLSupportMsgEvents\0IActMLSupportMsg\0varErrorCode\0QVariant&\0lpvarErrorMessage\0"
    "ActSupportMsgLib::IActMLSupportMsg\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_ActSupportMsgLib__ActSupportMsg[] = {

 // content:
    7, // revision
    0,  // classname
    2, 14, // classinfo
    4, 18, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 2, 
    3, 4, 

// signal: name, argc, parameters, tag, flags
    5, 4, 38, 6, 5,
    11, 1, 47, 6, 5,
    13, 3, 50, 6, 5,

// slot: name, argc, parameters, tag, flags
    16, 2, 57, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 7, 8, 9, 10,
    QMetaType::Void, QMetaType::QString, 12,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 12, 14, 15,

// slot: parameters
    QMetaType::Int, QMetaType::Int, 0x80000000 | 18, 17, 19,

    0 // eod
};

ActSupportMsg::ActSupportMsg(QWidget *parent, Qt::WindowFlags f) :
    QAxWidget(parent, f)
{
    setControl(QStringLiteral("{15c5a7a2-53a5-445c-b294-f383f951ac92}"));
}

const QMetaObject ActSupportMsg::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ActSupportMsgLib__ActSupportMsg, nullptr, nullptr, nullptr }
};

void *ActSupportMsg::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "ActSupportMsgLib::ActSupportMsg"))
        return static_cast<void*>(const_cast<ActSupportMsg*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_ActSupportMsgLib__IActSupportMsg[] = {

 // content:
    7, // revision
    20,  // classname
    0, 0, // classinfo
    4, 14, // methods
    1, 58, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    5, 4, 34, 6, 5,
    11, 1, 43, 6, 5,
    13, 3, 46, 6, 5,

// slot: name, argc, parameters, tag, flags
    16, 2, 53, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 7, 8, 9, 10,
    QMetaType::Void, QMetaType::QString, 12,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 12, 14, 15,

// slot: parameters
    QMetaType::Int, QMetaType::Int, 0x80000000 | 18, 17, 19,

 // properties: name, type, flags
    21, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

IActSupportMsg::IActSupportMsg(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject IActSupportMsg::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ActSupportMsgLib__IActSupportMsg, nullptr, nullptr, nullptr }
};

void *IActSupportMsg::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "ActSupportMsgLib::IActSupportMsg"))
        return static_cast<void*>(const_cast<IActSupportMsg*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_ActSupportMsgLib__ActMLSupportMsg[] = {

 // content:
    7, // revision
    22,  // classname
    2, 14, // classinfo
    4, 18, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 23, 
    3, 24, 

// signal: name, argc, parameters, tag, flags
    5, 4, 38, 6, 5,
    11, 1, 47, 6, 5,
    13, 3, 50, 6, 5,

// slot: name, argc, parameters, tag, flags
    16, 2, 57, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 7, 8, 9, 10,
    QMetaType::Void, QMetaType::QString, 12,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 12, 14, 15,

// slot: parameters
    QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 26, 25, 27,

    0 // eod
};

ActMLSupportMsg::ActMLSupportMsg(QWidget *parent, Qt::WindowFlags f) :
    QAxWidget(parent, f)
{
    setControl(QStringLiteral("{ae77fcc7-a9dc-4a11-a25c-04b7c44e32e6}"));
}

const QMetaObject ActMLSupportMsg::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ActSupportMsgLib__ActMLSupportMsg, nullptr, nullptr, nullptr }
};

void *ActMLSupportMsg::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "ActSupportMsgLib::ActMLSupportMsg"))
        return static_cast<void*>(const_cast<ActMLSupportMsg*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_ActSupportMsgLib__IActMLSupportMsg[] = {

 // content:
    7, // revision
    28,  // classname
    0, 0, // classinfo
    4, 14, // methods
    1, 58, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    5, 4, 34, 6, 5,
    11, 1, 43, 6, 5,
    13, 3, 46, 6, 5,

// slot: name, argc, parameters, tag, flags
    16, 2, 53, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 7, 8, 9, 10,
    QMetaType::Void, QMetaType::QString, 12,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 12, 14, 15,

// slot: parameters
    QMetaType::QVariant, QMetaType::QVariant, 0x80000000 | 26, 25, 27,

 // properties: name, type, flags
    21, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

IActMLSupportMsg::IActMLSupportMsg(IDispatch *subobject, QAxObject *parent) :
    QAxObject(subobject, parent)
{
    internalRelease();
}

const QMetaObject IActMLSupportMsg::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ActSupportMsgLib__IActMLSupportMsg, nullptr, nullptr, nullptr }
};

void *IActMLSupportMsg::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, "ActSupportMsgLib::IActMLSupportMsg"))
        return static_cast<void*>(const_cast<IActMLSupportMsg*>(this));
    return QAxObject::qt_metacast(_clname);
}

