/****************************************************************************
**
** Namespace ActSupportMsgLib generated by dumpcpp v5.14.2 using
** dumpcpp.exe {15C5A7A2-53A5-445C-B294-F383F951AC92}
** from the type library E:\MX Componetnt 4.19v\Act\Control\ActSupportMsg.dll
**
****************************************************************************/

#ifndef QAX_DUMPCPP_ACTSUPPORTMSGLIB_H
#define QAX_DUMPCPP_ACTSUPPORTMSGLIB_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef ACTSUPPORTMSGLIB_EXPORT
#define ACTSUPPORTMSGLIB_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace

namespace ActSupportMsgLib {


// skipping event interface _IActSupportMsgEvents

class ACTSUPPORTMSGLIB_EXPORT IActSupportMsg : public QAxObject
{
public:
    explicit IActSupportMsg(IDispatch *subobject = nullptr, QAxObject *parent = nullptr);
    /*
    Method GetErrorMessage

    Method GetErrorMessage

    */
    inline int GetErrorMessage(int lErrorCode, QString& lpszErrorMessage);

// meta object functions
    static const QMetaObject staticMetaObject;
    const QMetaObject *metaObject() const override { return &staticMetaObject; }
    void *qt_metacast(const char *) override;
};

// skipping event interface _IActMLSupportMsgEvents

class ACTSUPPORTMSGLIB_EXPORT IActMLSupportMsg : public QAxObject
{
public:
    explicit IActMLSupportMsg(IDispatch *subobject = nullptr, QAxObject *parent = nullptr);
    /*
    Method GetErrorMessage

    Method GetErrorMessage

    */
    inline QVariant GetErrorMessage(const QVariant& varErrorCode, QVariant& lpvarErrorMessage);

// meta object functions
    static const QMetaObject staticMetaObject;
    const QMetaObject *metaObject() const override { return &staticMetaObject; }
    void *qt_metacast(const char *) override;
};

// Actual coclasses
class ACTSUPPORTMSGLIB_EXPORT ActSupportMsg : public QAxWidget
{
public:
    explicit ActSupportMsg(QWidget *parent = nullptr, Qt::WindowFlags f = {});
    ActSupportMsg(IActSupportMsg *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Method GetErrorMessage

    Method GetErrorMessage

    */
    inline int GetErrorMessage(int lErrorCode, QString& lpszErrorMessage);

// meta object functions
    static const QMetaObject staticMetaObject;
    const QMetaObject *metaObject() const override { return &staticMetaObject; }
    void *qt_metacast(const char *) override;
};

class ACTSUPPORTMSGLIB_EXPORT ActMLSupportMsg : public QAxWidget
{
public:
    explicit ActMLSupportMsg(QWidget *parent = nullptr, Qt::WindowFlags f = {});
    ActMLSupportMsg(IActMLSupportMsg *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Method GetErrorMessage

    Method GetErrorMessage

    */
    inline QVariant GetErrorMessage(const QVariant& varErrorCode, QVariant& lpvarErrorMessage);

// meta object functions
    static const QMetaObject staticMetaObject;
    const QMetaObject *metaObject() const override { return &staticMetaObject; }
    void *qt_metacast(const char *) override;
};

// member function implementation
#ifndef QAX_DUMPCPP_ACTSUPPORTMSGLIB_NOINLINES
inline int ActSupportMsg::GetErrorMessage(int lErrorCode, QString& lpszErrorMessage)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lErrorCode, (void*)&lpszErrorMessage};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
    return qax_result;
}


inline int IActSupportMsg::GetErrorMessage(int lErrorCode, QString& lpszErrorMessage)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lErrorCode, (void*)&lpszErrorMessage};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}


inline QVariant ActMLSupportMsg::GetErrorMessage(const QVariant& varErrorCode, QVariant& lpvarErrorMessage)
{
    QVariant qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&varErrorCode, (void*)&lpvarErrorMessage};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
    return qax_result;
}


inline QVariant IActMLSupportMsg::GetErrorMessage(const QVariant& varErrorCode, QVariant& lpvarErrorMessage)
{
    QVariant qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&varErrorCode, (void*)&lpvarErrorMessage};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<ActSupportMsgLib::ActSupportMsg, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<ActSupportMsgLib::ActSupportMsg*>(t)->ActSupportMsgLib::ActSupportMsg::~ActSupportMsg();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) ActSupportMsgLib::ActSupportMsg;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const ActSupportMsgLib::ActSupportMsg*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<ActSupportMsgLib::ActSupportMsg*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<ActSupportMsgLib::IActSupportMsg, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<ActSupportMsgLib::IActSupportMsg*>(t)->ActSupportMsgLib::IActSupportMsg::~IActSupportMsg();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) ActSupportMsgLib::IActSupportMsg;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const ActSupportMsgLib::IActSupportMsg*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<ActSupportMsgLib::IActSupportMsg*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<ActSupportMsgLib::ActMLSupportMsg, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<ActSupportMsgLib::ActMLSupportMsg*>(t)->ActSupportMsgLib::ActMLSupportMsg::~ActMLSupportMsg();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) ActSupportMsgLib::ActMLSupportMsg;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const ActSupportMsgLib::ActMLSupportMsg*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<ActSupportMsgLib::ActMLSupportMsg*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<ActSupportMsgLib::IActMLSupportMsg, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<ActSupportMsgLib::IActMLSupportMsg*>(t)->ActSupportMsgLib::IActMLSupportMsg::~IActMLSupportMsg();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) ActSupportMsgLib::IActMLSupportMsg;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const ActSupportMsgLib::IActMLSupportMsg*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<ActSupportMsgLib::IActMLSupportMsg*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

